MERGE INTO ingredient (id, name, type) KEY(id) VALUES ('FLTO', 'Flour Tortilla', 'WRAP');
MERGE INTO ingredient (id, name, type) KEY(id) VALUES ('COTO', 'Corn Tortilla', 'WRAP');
MERGE INTO ingredient (id, name, type) KEY(id) VALUES ('GRBF', 'Ground Beef', 'PROTEIN');
MERGE INTO ingredient (id, name, type) KEY(id) VALUES ('CARN', 'Carnitas', 'PROTEIN');
MERGE INTO ingredient (id, name, type) KEY(id) VALUES ('TMTO', 'Diced Tomatoes', 'VEGGIES');
MERGE INTO ingredient (id, name, type) KEY(id) VALUES ('LETC', 'Lettuce', 'VEGGIES');
MERGE INTO ingredient (id, name, type) KEY(id) VALUES ('CHED', 'Cheddar', 'CHEESE');
MERGE INTO ingredient (id, name, type) KEY(id) VALUES ('JACK', 'Monterrey Jack', 'CHEESE');
MERGE INTO ingredient (id, name, type) KEY(id) VALUES ('SLSA', 'Salsa', 'SAUCE');
MERGE INTO ingredient (id, name, type) KEY(id) VALUES ('SRCR', 'Sour Cream', 'SAUCE');
